apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudapp-pv
  namespace: cloudapp
spec:
  accessModes:
    - ReadWriteMany
  capacity: 
    storage: 10Gi
  nfs:
    path: /nfs/cloudapp
    server: 192.168.109.156

